[package]
name = "arrs"
version = "0.1.0"
authors = ["Quinn Okabayashi <qokabay1@swarthmore.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.123"
